version: '3.1'
services:
  stats-server:
    build: ./stat-svc/stat-server
    image: stat-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore
      - SPRING_DATASOURCE_USERNAME=exploreUser
      - SPRING_DATASOURCE_PASSWORD=explorePass

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore
      - POSTGRES_USER=exploreUser
      - POSTGRES_PASSWORD=explorePass

  ewm-service:
    build: ./main-svc
    image: main-service
    container_name: ewm-service
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
